SMASH_CHARACTERS = {
    "Bayonetta" => "byo",
    "Bowser" => "bow",
    "Bowser Jr." => "bjr",
    "Captain Falcon" => "fcn",
    "Captain Olimar" => "olm",
    "Charizard" => "chr",
    "Chrom" => "chm",
    "Cloud" => "cld",
    "Corrin" => "crn",
    "Dark Pit" => "dpt",
    "Dark Samus" => "dks",
    "Diddy Kong" => "ddy",
    "Doctor Mario" => "doc",
    "Donkey Kong" => "dnk",
    "Duck Hunt" => "dck",
    "Falco" => "fco",
    "Fox" => "fox",
    "Ganondorf" => "gnn",
    "Greninja" => "grn",
    "Ice Climbers" => "ics",
    "Incineroar" => "inc",
    "Ike" => "ike",
    "Inkling" => "ink",
    "Ivysaur" => "ivy",
    "Jigglypuff" => "puf",
    "Joker" => "jok",
    "Ken" => "ken",
    "King Dedede" => "ddd",
    "King K. Rool" => "kkr",
    "Kirby" => "kby",
    "Link" => "lnk",
    "Little Mac" => "lmc",
    "Lucario" => "lcr",
    "Lucas" => "lcs",
    "Lucina" => "lcn",
    "Luigi" => "lgi",
    "Mario" => "mar",
    "Marth" => "mrt",
    "Mega Man" => "meg",
    "Meta Knight" => "mtk",
    "Mewtwo" => "mw2",
    "Mii Brawler" => "mib",
    "Mii Gunner" => "mig",
    "Mii Swordfighter" => "mis",
    "Mr. Game & Watch" => "gnw",
    "Ness" => "nes",
    "Pac-Man" => "pac",
    "Palutena" => "pal",
    "Peach" => "pch",
    "Pichu" => "pic",
    "Pikachu" => "pik",
    "Piranha Plant" => "pir",
    "Pit" => "pit",
    "Pokémon Trainer" => "pkt",
    "Ricter" => "ric",
    "Ridley" => "rid",
    "R.O.B." => "rob",
    "Robin" => "rbn",
    "Rosalina" => "ros",
    "Roy" => "roy",
    "Ryu" => "ryu",
    "Samus" => "sam",
    "Sheik" => "shk",
    "Shulk" => "slk",
    "Simon" => "smn",
    "Snake" => "snk",
    "Sonic" => "snc",
    "Squirtle" => "sqt",
    "Toon Link" => "tlk",
    "Villager" => "vlg",
    "Wario" => "war",
    "Wii Fit Trainer" => "wft",
    "Wolf" => "wlf",
    "Yoshi" => "ysh",
    "Young Link" => "ylk",
    "Zelda" => "zld",
    "Zero Suit Samus" => "zss"
}

def get_smash_character(string)
    if string == nil || string.empty?
        return nil
    else
        return SMASH_CHARACTERS[string]
    end
end
